name: airvitals
description: A real-time environmental monitoring Flutter app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  equatable: ^2.0.7
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  firebase_database: ^11.3.0
  flex_color_scheme: ^8.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  get_it: ^8.0.3
  go_router: ^14.6.2
  injectable: ^2.3.2
  intl: ^0.19.0
  json_annotation: ^4.8.1


dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.4.5
  go_router_builder: ^2.4.1
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Noto Sans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans-Italic.ttf
          style: italic
