name: airvitals
description: A real-time environmental monitoring Flutter app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  cloud_firestore: ^5.6.0
  connectivity_plus: ^6.1.1
  drift: ^2.15.0
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  firebase_messaging: ^15.1.6
  fl_chart: ^0.70.0
  flex_color_scheme: ^8.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  get_it: ^8.0.3
  go_router: ^14.6.2
  injectable: ^2.3.2
  intl: ^0.19.0
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  path: ^1.8.3
  path_provider: ^2.1.2
  sqlite3_flutter_libs: ^0.5.20


dev_dependencies:
  build_runner: ^2.4.7
  #drift_dev: ^2.15.0
  flutter_lints: ^5.0.0
  freezed: ^2.4.5
  go_router_builder: ^2.4.1
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Noto Sans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans-Italic.ttf
          style: italic
